import {Producto} from "./producto";

export const PRODUCTOS:Producto[]=[
  new Producto(1,"Brazalete en mopa",10000,"El Barniz de Pasto, técina decorativa desarrolada por una de las comunidades indigenas de Nariño, en el sur de Colombia, es una de las ocas artesanías existentes en Colombia que tiene procedencia aborigen.","/app/imagenes/imgsThumbnail/1-brazalete.jpg","/app/imagenes/imgsGrandes/1-brazalete.jpg"),
  new Producto(2,"Abrecartas Carnaval",19000,"Considerado como uno de los carnavales más importantes de Colombia,el Carnaval de Barranquilla fue reconocido por la UNESCO como Patrimonio Oral e Inmaterial de la Humanidad.","/app/imagenes/imgsThumbnail/2-abrecartas.jpg","/app/imagenes/imgsGrandes/2-abrecartas.jpg"),
  new Producto(3,"Aguamanil Carmen de viboral",148000,"En el oriente Antioqueño se encuentra un pueblo de ceramistas llamado Carmen de viboral, famoso por fabricar vajillas de color blanco alegremente adornadas con diseños de diversas flores.","/app/imagenes/imgsThumbnail/3-aguamanil.jpg","/app/imagenes/imgsGrandes/3-aguamanil.jpg"),
  new Producto(4,"Alcaparras ceramicas",39000,"Julia Elisa Castillo se ha dedicado al oficio cerámico desde sus cuarenta años, el trabajo con arcilla surgió de la observación de la naturaleza en su propia cada en Guaduas, Cundinamarca, donde una escena doméstica inspiró la estética central en la obra","/app/imagenes/imgsThumbnail/4-alcaparras.jpg","/app/imagenes/imgsGrandes/4-alcaparras.jpg"),
  new Producto(5,"Balay Mediano",84000,"En la grandeza de la selva Amázonica convive una diversidad de etnias indígenas que, a pesar de sus diferentes formas de vida, comparten algnas prácticas como la cestería.","/app/imagenes/imgsThumbnail/5-balay_mediano.png","/app/imagenes/imgsGrandes/5-balay_mediano.png"),
  new Producto(6,"Balay Pequeño",41000,"En la grandeza de la selva Amázonica convive una diversidad de etnias indígenas que, a pesar de sus diferentes formas de vida, comparten algnas prácticas como la cestería.","/app/imagenes/imgsThumbnail/6-balay_pequeño.png","/app/imagenes/imgsGrandes/6-balay_pequeño.png"),
  new Producto(7,"Balay Grande",133000,"En la grandeza de la selva Amázonica convive una diversidad de etnias indígenas que, a pesar de sus diferentes formas de vida, comparten algnas prácticas como la cestería.","/app/imagenes/imgsThumbnail/7-balay_grande.png","/app/imagenes/imgsGrandes/ 7-balay_grande.png"),
  new Producto(8,"Butaco Kátmenza",270000,"En numerosas etnias del contexto selvático del país, los bancos en madera hacen parte de la esfera ritual, Tallados en una sola pieza de madera por los hombres, ofrecen un espacio apropiado para que los chamanes o guías espirituales pueden sentarse a pensar, cantar y curar.","/app/imagenes/imgsThumbnail/8-butaco_kamentza.jpg","/app/imagenes/imgsGrandes/8-butaco_kamentza.jpg"),
  new Producto(9,"Banco Tucano",82000,"En la grandeza de la selva Amázonica convive una diversidad de etnias indígenas que, a pesar de sus diferentes formas de vida, comparten algnas prácticas como la cestería.","/app/imagenes/imgsThumbnail/9-bancotucano.jpg","/app/imagenes/imgsGrandes/9-bancotucano.jpg"),
  new Producto(10,"Bandeja Resina",158000,"Pedro africano es uno de los maestro más reconocidos en el arte del enchape, técnica  con la cual recubre la madera con los diversos materiales de origen natural, entre los cuales destacan: bambú, oco, bejuco, totumo, papiro y tagua.","/app/imagenes/imgsThumbnail/10-bandeja_resina.jpg","/app/imagenes/imgsGrandes/10-bandeja_resina.jpg"),
  new Producto(11,"Bandeja Werregue",160000,"Al interior de las selvas chocoanas habitan los indígenas Wounaan o Noanamá, reconocidos en el mundo artesanal por la finura de sus canastos o cocas de Werregue. Son gente de agua y de monte que están asentados sobre las riveras del Bajo San Juan y hatiban la cuenca hasta su desembocadura.","/app/imagenes/imgsThumbnail/11-bandeja_werregue.jpg","/app/imagenes/imgsGrandes/11-bandeja_werregue.jpg"),
  new Producto(12,"Batea Cuadrada",188000,"Pedro africano es uno de los maestro más reconocidos en el arte del enchape, técnica  con la cual recubre la madera con los diversos materiales de origen natural, entre los cuales destacan: bambú, oco, bejuco, totumo, papiro y tagua.","/app/imagenes/imgsThumbnail/12-batea_cuadrada.png","/app/imagenes/imgsGrandes/12-batea_cuadrada.png"),
  new Producto(13,"Baúl Iraca",220000,"Conocido por el trabajo de la palma de iraca para la elaboración de sombreros y diversidad de cestos Sandoá, municipio situado en el departamento de Nariño al sur del pais es heredero de las técnias de sus antepasados quillacingas para el manejo de dicha fibra vegetal.","/app/imagenes/imgsThumbnail/13-baul_iraca.png","/app/imagenes/imgsGrandes/13-baul_iraca.png"),
  new Producto(14,"Billeteras Yanchama",19000,"El trapecio amazónico, territorio de selva y biodiversidad, alberga una gran cantidad de grupos indígenas que habitan en Malocas. Los Tukano, Huitoto, Ocaina, Tikuna y Cocama extraen materias prímas de su entorno para elaborar artesanías similares, en las que cada gruop plasma sus propias cosmovisiones.","/app/imagenes/imgsThumbnail/14-billeteras_Yanchama.jpg","/app/imagenes/imgsGrandes/14-billeteras_Yanchama.jpg"),
  new Producto(15,"Bolso Iraca Mediano",71900,"Conocido por el trabajo de la palma de iraca para la elaboración de sombreros y diversidad de cestos Sandoá, municipio situado en el departamento de Nariño al sur del pais es heredero de las técnias de sus antepasados quillacingas para el manejo de dicha fibra vegetal.","/app/imagenes/imgsThumbnail/15-bolso_iraca_mediano.jpg","/app/imagenes/imgsGrandes/15-bolso_iraca_mediano.jpg"),
  new Producto(16,"Gallina Sopera",82000,"Julia Elisa Castillo se ha dedicado al oficio cerámico desde sus cuarenta años, el trabajo con arcilla surgió de la observación de la naturaleza en su propia cada en Guaduas, Cundinamarca, donde una escena doméstica inspiró la estética central en la obra","/app/imagenes/imgsThumbnail/16-gallina_sopera.png","/app/imagenes/imgsGrandes/16-gallina_sopera.png"),
  new Producto(17,"Memoria USB",72000,"Memoria de 2GB con representaciones de las máscaras tradicionales del carnaval de Barranquilla.","/app/imagenes/imgsThumbnail/17-memoria_usb.png","/app/imagenes/imgsGrandes/17-memoria_usb.png"),
  new Producto(18,"Mula de papel mache",45000,"Mula elaborada en papel maché por Alvaro Montes en la ciudad de Manizales. Representa el medio tradicional de carga de la región cafetera.","/app/imagenes/imgsThumbnail/18-mula_papel_mache.png","/app/imagenes/imgsGrandes/18-mula_papel_mache.png")

];



